@serverUrl = http://localhost:5001/api

POST http://localhost:5001/api/auth/register
Content-Type: application/json

{
  "email":"vinhngotrung1999@gmail.com",
  "fullname":"Ngô Trung Vinh",
  "username": "vinhngo",
  "password": "123456"
}

###

POST {{serverUrl}}/auth/login
Content-Type: application/json

{
  "account": "vinhngo",
  "password": "123456"
}

###

POST {{serverUrl}}/auth/active
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsbmFtZSI6Ik5nw7QgVHJ1bmcgVmluaCIsInVzZXJuYW1lIjoidmluaG5nbyIsImVtYWlsIjoidmluaG5nb3RydW5nMTk5OUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCR1c3JjNEJzTWZNejVBbHZqWVlqRzEuazFzLmlneDJsbG9tcVEzckhmNjdqNDdMaUZWWjBzcSIsInNhbHQiOiIkMmIkMTAkdXNyYzRCc01mTXo1QWx2allZakcxLiIsImlhdCI6MTY4MDMxNjI5NiwiZXhwIjoxNjgwMzE3MTk2fQ.d2qd8JSZHSgVAO9lOkgjpwgdzaHZy4SWl3anUL5D66I"
}

###

POST {{serverUrl}}/auth/refresh-token
Content-Type: application/json
###

POST {{serverUrl}}/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDFlYTRjYTc1MGI4NjI2YzAzYTEwYzYiLCJpYXQiOjE2ODAzMTc3OTksImV4cCI6MTY4MDQwNDE5OX0.MjgR_ioAETk3QR2pL4j2rM6ZgnC6vL3NEEvkIW11_xM
###

POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDYxYjk1YjdkMjljZTFiMTA5YmQxZTAiLCJpYXQiOjE2MTczNjIxNjV9.ZTwbrIeDpchmUjkNQv_bmBd7_Maw2Gp7Y1ioZx2s7i8

{
  "title": "React",
  "description": "React",
  "url": "react.com",
  "status": "TO LEARN"
}

###

GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDYxYjk1YjdkMjljZTFiMTA5YmQxZTAiLCJpYXQiOjE2MTcwMTk3ODF9.ri-nHdgZc1VQTocFLfMgF4_PhFf2TeUVqXLd8tpOkeA

###

PUT http://localhost:5000/api/posts/6061c25ac2533d41dcae2b19
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDYxYjk1YjdkMjljZTFiMTA5YmQxZTAiLCJpYXQiOjE2MTcwMTk3ODF9.ri-nHdgZc1VQTocFLfMgF4_PhFf2TeUVqXLd8tpOkeA

{
  "title": "Vue",
  "description": "VUEEEEE",
  "url": "https://vuejs.org",
  "status": "LEARNING"
}

###

DELETE http://localhost:5000/api/posts/6061c25ac2533d41dcae2b19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDYxYjk1YjdkMjljZTFiMTA5YmQxZTAiLCJpYXQiOjE2MTcwMTk3ODF9.ri-nHdgZc1VQTocFLfMgF4_PhFf2TeUVqXLd8tpOkeA
