export const GLOBALTYPES = {
  AUTH: 'AUTH',
  ALERT: 'ALERT',
  THEME: 'THEME',
  STATUS: 'STATUS',
  MODAL: 'MODAL',
  SOCKET: 'SOCKET',
  ONLINE: 'ONLINE',
  OFFLINE: 'OFFLINE',
  CALL: 'CALL',
  PEER: 'PEER',
  SIDEBAR: 'SIDEBAR',
};

export const MESSAGE_TYPES = {
  GET_MESSAGES: 'GET_MESSAGES',
  GET_CONVERSATIONS: 'GET_CONVERSATIONS',
  CREATE_MESSAGE: 'CREATE_MESSAGES',
  ADD_USER: 'ADD_USER',
  CHECK_ONLINE_OFFLINE: 'CHECK_ONLINE_OFFLINE',
  DELETE_MESSAGE: 'DELETE_MESSAGE',
  EDIT_MESSAGE: 'EDIT_MESSAGE',
  DELETE_CV: 'DELETE_CV',
  UPDATE_MESSAGE_ID: 'UPDATE_MESSAGE_ID',
  DELETE_TEMP_MESSAGE: 'DELETE_TEMP_MESSAGE',
  MARK_TEMP_MESSAGE_DELETED: 'MARK_TEMP_MESSAGE_DELETED',
};

export const SOCIAL_TYPES = {
  LOADING: 'LOADING_SOCIAL',
  GET_SOCIAL_STATS: 'GET_SOCIAL',
  UPDATE_SOCIAL_STATS: 'UPDATE_SOCIAL',
  UPDATE_GITHUB_STATS: 'UPDATE_GITHUB_STATS',
  UPDATE_YT_STATS: 'UPDATE_YT_STATS',
};

export const editData = (data, id, post) => {
  return data.map(item => (item._id === id ? post : item));
};

export const deleteData = (data, id) => {
  return data.filter(item => item._id !== id);
};
