const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',

    GET_ALL_ROLES: 'GET_ALL_ROLES',
    CREATE_ROLE: 'CREATE_ROLE',
    UPDATE_ROLE: 'UPDATE_ROLE',
    DELETE_ROLE: 'DELETE_ROLE',

    GET_ALL_CAPACITIES: 'GET_ALL_CAPACITIES',
    CREATE_CAPACITY: 'CREATE_CAPACITY',
    UPDATE_CAPACITY: 'UPDATE_CAPACITY',
    DELETE_CAPACITY: 'DELETE_CAPACITY',
}

export default ACTIONS;